#!/bin/sh

# CERT_PATH
# CA_CERT_PATH
# CERT_FULLCHAIN_PATH
# CERT_KEY_PATH
# Le_Domain

if [ "$Le_Domain" = 'example.com' ]; then
	logger -t 'acme' "running reload script ($0)"

	# Restart WebGUI
	service restart_httpd

	# Restart nginx
	[ -x '/opt/etc/init.d/S80nginx' ] && /opt/etc/init.d/S80nginx restart

	# Update Printer
	DOMAIN='hp.lan'

	# Grab the IP manually just in case local resolution is off
	IP="$(nslookup "$DOMAIN" '127.0.0.1' | awk 'NR>2&&/^Address/{print $(NF==2?2:3);exit}')"
	if ping -q -c 1 -w 1 "$IP" &>/dev/null; then
		# Use a random password
		PASSWORD="$(tr -dc 'A-F0-9' < /dev/urandom | dd bs=1c count=8 2>/dev/null)"

		# Convert to PKCS#12 so printer can read it
		openssl pkcs12 -export -in "$CERT_PATH" -inkey "$CERT_KEY_PATH" -certfile "$CA_CERT_PATH" -passout "pass:$PASSWORD" -out '/tmp/printer.pfx'

		# Upload to printer
		curl -Lks -o /dev/null -F 'FileName=@/tmp/printer.pfx' -F "Password=$PASSWORD" -F 'Finish=Finish' "https://$IP/hp/device/Certificate.pfx"

		# remove PKCS#12 file
		rm -f '/tmp/printer.pfx'
	fi
fi
