#!/bin/sh

if [ "$1" = 'start' ]; then
	case "$2" in
		'firewall')
			sleep 5
			service start_firewall
		;;
		'dhcp6c')
			sleep 30
			if ! pidof odhcp6c &>/dev/null; then
				service start_dhcp6c
			fi
		;;
	esac
fi
