#!/bin/sh

if [ "$1" = 'start' ]; then
	case "$2" in
		'firewall')
			sleep 5
			service start_firewall
		;;
		'dhcp6c')
			sleep 30
			if [ -z "$(ps | awk '{if(NR==1)c=index($0,"COMMAND");else if(substr($0,c)~p){print $1}}' p='^odhcp6c')" ]; then
				service start_dhcp6c
			fi
		;;
	esac
fi
